version: "3.8"

services:
  whisper-ui:
    image: hayabhay/whisper-ui
    build: .
    container_name: whisper-ui
    volumes:
      - whisper-data:/data
    restart: unless-stopped
    ports:
      - 8501:8501

volumes:
  whisper-data:
